FROM oven/bun:1-alpine AS builder

WORKDIR /app

COPY package.json ./
COPY bun.lock ./

ARG DATABASE_URL
ARG ENCRYPTION_KEY
ARG HMAC_KEY
ARG ENCRYPTION_METHOD
ARG IV_LENGTH
ARG KDF_SALT
ARG BASE_URL
ARG DISCORD_CLIENT_ID
ARG DISCORD_CLIENT_SECRET
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG RAILWAY_CLIENT_ID
ARG RAILWAY_CLIENT_SECRET
ARG BETTER_AUTH_SECRET
ARG ENVIRONMENT

ENV DATABASE_URL=${DATABASE_URL}
ENV ENCRYPTION_KEY=${ENCRYPTION_KEY}
ENV HMAC_KEY=${HMAC_KEY}
ENV ENCRYPTION_METHOD=${ENCRYPTION_METHOD}
ENV IV_LENGTH=${IV_LENGTH}
ENV KDF_SALT=${KDF_SALT}
ENV BASE_URL=${BASE_URL}
ENV DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
ENV DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
ENV GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
ENV GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
ENV RAILWAY_CLIENT_ID=${RAILWAY_CLIENT_ID}
ENV RAILWAY_CLIENT_SECRET=${RAILWAY_CLIENT_SECRET}
ENV BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
ENV ENVIRONMENT=${ENVIRONMENT}

RUN bun install --frozen-lockfile

COPY . .

RUN bun run build


FROM oven/bun:1-alpine AS runner

WORKDIR /app

COPY --from=builder /app/.output ./.output

EXPOSE 3000

CMD ["bun", "run", ".output/server/index.mjs"]