services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - ENCRYPTION_KEY=${ENCRYPTION_KEY}
        - HMAC_KEY=${HMAC_KEY}
        - ENCRYPTION_METHOD=${ENCRYPTION_METHOD}
        - IV_LENGTH=${IV_LENGTH}
        - KDF_SALT=${KDF_SALT}
        - BASE_URL=${BASE_URL}
        - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
        - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
        - RAILWAY_CLIENT_ID=${RAILWAY_CLIENT_ID}
        - RAILWAY_CLIENT_SECRET=${RAILWAY_CLIENT_SECRET}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
        - ENVIRONMENT=${ENVIRONMENT}
    restart: unless-stopped
    environment:
        - DATABASE_URL=${DATABASE_URL}
        - ENCRYPTION_KEY=${ENCRYPTION_KEY}
        - HMAC_KEY=${HMAC_KEY}
        - ENCRYPTION_METHOD=${ENCRYPTION_METHOD}
        - IV_LENGTH=${IV_LENGTH}
        - KDF_SALT=${KDF_SALT}
        - BASE_URL=${BASE_URL}
        - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
        - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
        - RAILWAY_CLIENT_ID=${RAILWAY_CLIENT_ID}
        - RAILWAY_CLIENT_SECRET=${RAILWAY_CLIENT_SECRET}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
        - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "${PORT}:${PORT}"
