/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as ApiHealthIndexRouteImport } from './routes/api/health/index'
import { Route as ProtectedAccountIndexRouteImport } from './routes/_protected/account/index'
import { Route as ProtectedProviderIdIndexRouteImport } from './routes/_protected/$providerId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiS3FilesIndexRouteImport } from './routes/api/s3/files/index'
import { Route as ApiS3CredentialIndexRouteImport } from './routes/api/s3/credential/index'
import { Route as ApiS3BucketsIndexRouteImport } from './routes/api/s3/buckets/index'
import { Route as ApiS3AccountsIndexRouteImport } from './routes/api/s3/accounts/index'
import { Route as ProtectedAccountManageS3IndexRouteImport } from './routes/_protected/account/manage-s3/index'
import { Route as ProtectedProviderIdBucketIdIndexRouteImport } from './routes/_protected/$providerId/$bucketId/index'
import { Route as ApiS3FilesDownloadIndexRouteImport } from './routes/api/s3/files/download/index'
import { Route as ApiS3BucketsRefetchIndexRouteImport } from './routes/api/s3/buckets/refetch/index'
import { Route as ApiS3BucketsRefetchProviderIdIndexRouteImport } from './routes/api/s3/buckets/refetch/$providerId/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiHealthIndexRoute = ApiHealthIndexRouteImport.update({
  id: '/api/health/',
  path: '/api/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountIndexRoute = ProtectedAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAccountRoute,
} as any)
const ProtectedProviderIdIndexRoute =
  ProtectedProviderIdIndexRouteImport.update({
    id: '/$providerId/',
    path: '/$providerId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiS3FilesIndexRoute = ApiS3FilesIndexRouteImport.update({
  id: '/api/s3/files/',
  path: '/api/s3/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiS3CredentialIndexRoute = ApiS3CredentialIndexRouteImport.update({
  id: '/api/s3/credential/',
  path: '/api/s3/credential/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiS3BucketsIndexRoute = ApiS3BucketsIndexRouteImport.update({
  id: '/api/s3/buckets/',
  path: '/api/s3/buckets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiS3AccountsIndexRoute = ApiS3AccountsIndexRouteImport.update({
  id: '/api/s3/accounts/',
  path: '/api/s3/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountManageS3IndexRoute =
  ProtectedAccountManageS3IndexRouteImport.update({
    id: '/manage-s3/',
    path: '/manage-s3/',
    getParentRoute: () => ProtectedAccountRoute,
  } as any)
const ProtectedProviderIdBucketIdIndexRoute =
  ProtectedProviderIdBucketIdIndexRouteImport.update({
    id: '/$providerId/$bucketId/',
    path: '/$providerId/$bucketId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ApiS3FilesDownloadIndexRoute = ApiS3FilesDownloadIndexRouteImport.update({
  id: '/api/s3/files/download/',
  path: '/api/s3/files/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiS3BucketsRefetchIndexRoute =
  ApiS3BucketsRefetchIndexRouteImport.update({
    id: '/api/s3/buckets/refetch/',
    path: '/api/s3/buckets/refetch/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiS3BucketsRefetchProviderIdIndexRoute =
  ApiS3BucketsRefetchProviderIdIndexRouteImport.update({
    id: '/api/s3/buckets/refetch/$providerId/',
    path: '/api/s3/buckets/refetch/$providerId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/account': typeof ProtectedAccountRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$providerId/': typeof ProtectedProviderIdIndexRoute
  '/account/': typeof ProtectedAccountIndexRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/$providerId/$bucketId/': typeof ProtectedProviderIdBucketIdIndexRoute
  '/account/manage-s3/': typeof ProtectedAccountManageS3IndexRoute
  '/api/s3/accounts/': typeof ApiS3AccountsIndexRoute
  '/api/s3/buckets/': typeof ApiS3BucketsIndexRoute
  '/api/s3/credential/': typeof ApiS3CredentialIndexRoute
  '/api/s3/files/': typeof ApiS3FilesIndexRoute
  '/api/s3/buckets/refetch/': typeof ApiS3BucketsRefetchIndexRoute
  '/api/s3/files/download/': typeof ApiS3FilesDownloadIndexRoute
  '/api/s3/buckets/refetch/$providerId/': typeof ApiS3BucketsRefetchProviderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/about': typeof AboutIndexRoute
  '/signin': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$providerId': typeof ProtectedProviderIdIndexRoute
  '/account': typeof ProtectedAccountIndexRoute
  '/api/health': typeof ApiHealthIndexRoute
  '/$providerId/$bucketId': typeof ProtectedProviderIdBucketIdIndexRoute
  '/account/manage-s3': typeof ProtectedAccountManageS3IndexRoute
  '/api/s3/accounts': typeof ApiS3AccountsIndexRoute
  '/api/s3/buckets': typeof ApiS3BucketsIndexRoute
  '/api/s3/credential': typeof ApiS3CredentialIndexRoute
  '/api/s3/files': typeof ApiS3FilesIndexRoute
  '/api/s3/buckets/refetch': typeof ApiS3BucketsRefetchIndexRoute
  '/api/s3/files/download': typeof ApiS3FilesDownloadIndexRoute
  '/api/s3/buckets/refetch/$providerId': typeof ApiS3BucketsRefetchProviderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/account': typeof ProtectedAccountRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/about/': typeof AboutIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/$providerId/': typeof ProtectedProviderIdIndexRoute
  '/_protected/account/': typeof ProtectedAccountIndexRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/_protected/$providerId/$bucketId/': typeof ProtectedProviderIdBucketIdIndexRoute
  '/_protected/account/manage-s3/': typeof ProtectedAccountManageS3IndexRoute
  '/api/s3/accounts/': typeof ApiS3AccountsIndexRoute
  '/api/s3/buckets/': typeof ApiS3BucketsIndexRoute
  '/api/s3/credential/': typeof ApiS3CredentialIndexRoute
  '/api/s3/files/': typeof ApiS3FilesIndexRoute
  '/api/s3/buckets/refetch/': typeof ApiS3BucketsRefetchIndexRoute
  '/api/s3/files/download/': typeof ApiS3FilesDownloadIndexRoute
  '/api/s3/buckets/refetch/$providerId/': typeof ApiS3BucketsRefetchProviderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/about/'
    | '/signin/'
    | '/api/auth/$'
    | '/$providerId/'
    | '/account/'
    | '/api/health/'
    | '/$providerId/$bucketId/'
    | '/account/manage-s3/'
    | '/api/s3/accounts/'
    | '/api/s3/buckets/'
    | '/api/s3/credential/'
    | '/api/s3/files/'
    | '/api/s3/buckets/refetch/'
    | '/api/s3/files/download/'
    | '/api/s3/buckets/refetch/$providerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/signin'
    | '/api/auth/$'
    | '/$providerId'
    | '/account'
    | '/api/health'
    | '/$providerId/$bucketId'
    | '/account/manage-s3'
    | '/api/s3/accounts'
    | '/api/s3/buckets'
    | '/api/s3/credential'
    | '/api/s3/files'
    | '/api/s3/buckets/refetch'
    | '/api/s3/files/download'
    | '/api/s3/buckets/refetch/$providerId'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/account'
    | '/_protected/'
    | '/about/'
    | '/signin/'
    | '/api/auth/$'
    | '/_protected/$providerId/'
    | '/_protected/account/'
    | '/api/health/'
    | '/_protected/$providerId/$bucketId/'
    | '/_protected/account/manage-s3/'
    | '/api/s3/accounts/'
    | '/api/s3/buckets/'
    | '/api/s3/credential/'
    | '/api/s3/files/'
    | '/api/s3/buckets/refetch/'
    | '/api/s3/files/download/'
    | '/api/s3/buckets/refetch/$providerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthIndexRoute: typeof ApiHealthIndexRoute
  ApiS3AccountsIndexRoute: typeof ApiS3AccountsIndexRoute
  ApiS3BucketsIndexRoute: typeof ApiS3BucketsIndexRoute
  ApiS3CredentialIndexRoute: typeof ApiS3CredentialIndexRoute
  ApiS3FilesIndexRoute: typeof ApiS3FilesIndexRoute
  ApiS3BucketsRefetchIndexRoute: typeof ApiS3BucketsRefetchIndexRoute
  ApiS3FilesDownloadIndexRoute: typeof ApiS3FilesDownloadIndexRoute
  ApiS3BucketsRefetchProviderIdIndexRoute: typeof ApiS3BucketsRefetchProviderIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/api/health'
      fullPath: '/api/health/'
      preLoaderRoute: typeof ApiHealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account/': {
      id: '/_protected/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof ProtectedAccountIndexRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/_protected/$providerId/': {
      id: '/_protected/$providerId/'
      path: '/$providerId'
      fullPath: '/$providerId/'
      preLoaderRoute: typeof ProtectedProviderIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3/files/': {
      id: '/api/s3/files/'
      path: '/api/s3/files'
      fullPath: '/api/s3/files/'
      preLoaderRoute: typeof ApiS3FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3/credential/': {
      id: '/api/s3/credential/'
      path: '/api/s3/credential'
      fullPath: '/api/s3/credential/'
      preLoaderRoute: typeof ApiS3CredentialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3/buckets/': {
      id: '/api/s3/buckets/'
      path: '/api/s3/buckets'
      fullPath: '/api/s3/buckets/'
      preLoaderRoute: typeof ApiS3BucketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3/accounts/': {
      id: '/api/s3/accounts/'
      path: '/api/s3/accounts'
      fullPath: '/api/s3/accounts/'
      preLoaderRoute: typeof ApiS3AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account/manage-s3/': {
      id: '/_protected/account/manage-s3/'
      path: '/manage-s3'
      fullPath: '/account/manage-s3/'
      preLoaderRoute: typeof ProtectedAccountManageS3IndexRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/_protected/$providerId/$bucketId/': {
      id: '/_protected/$providerId/$bucketId/'
      path: '/$providerId/$bucketId'
      fullPath: '/$providerId/$bucketId/'
      preLoaderRoute: typeof ProtectedProviderIdBucketIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/s3/files/download/': {
      id: '/api/s3/files/download/'
      path: '/api/s3/files/download'
      fullPath: '/api/s3/files/download/'
      preLoaderRoute: typeof ApiS3FilesDownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3/buckets/refetch/': {
      id: '/api/s3/buckets/refetch/'
      path: '/api/s3/buckets/refetch'
      fullPath: '/api/s3/buckets/refetch/'
      preLoaderRoute: typeof ApiS3BucketsRefetchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3/buckets/refetch/$providerId/': {
      id: '/api/s3/buckets/refetch/$providerId/'
      path: '/api/s3/buckets/refetch/$providerId'
      fullPath: '/api/s3/buckets/refetch/$providerId/'
      preLoaderRoute: typeof ApiS3BucketsRefetchProviderIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedAccountRouteChildren {
  ProtectedAccountIndexRoute: typeof ProtectedAccountIndexRoute
  ProtectedAccountManageS3IndexRoute: typeof ProtectedAccountManageS3IndexRoute
}

const ProtectedAccountRouteChildren: ProtectedAccountRouteChildren = {
  ProtectedAccountIndexRoute: ProtectedAccountIndexRoute,
  ProtectedAccountManageS3IndexRoute: ProtectedAccountManageS3IndexRoute,
}

const ProtectedAccountRouteWithChildren =
  ProtectedAccountRoute._addFileChildren(ProtectedAccountRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedProviderIdIndexRoute: typeof ProtectedProviderIdIndexRoute
  ProtectedProviderIdBucketIdIndexRoute: typeof ProtectedProviderIdBucketIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedProviderIdIndexRoute: ProtectedProviderIdIndexRoute,
  ProtectedProviderIdBucketIdIndexRoute: ProtectedProviderIdBucketIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthIndexRoute: ApiHealthIndexRoute,
  ApiS3AccountsIndexRoute: ApiS3AccountsIndexRoute,
  ApiS3BucketsIndexRoute: ApiS3BucketsIndexRoute,
  ApiS3CredentialIndexRoute: ApiS3CredentialIndexRoute,
  ApiS3FilesIndexRoute: ApiS3FilesIndexRoute,
  ApiS3BucketsRefetchIndexRoute: ApiS3BucketsRefetchIndexRoute,
  ApiS3FilesDownloadIndexRoute: ApiS3FilesDownloadIndexRoute,
  ApiS3BucketsRefetchProviderIdIndexRoute:
    ApiS3BucketsRefetchProviderIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
