/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as ApiHealthIndexRouteImport } from './routes/api/health/index'
import { Route as ProtectedAccountIndexRouteImport } from './routes/_protected/account/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiS3AccountsIndexRouteImport } from './routes/api/s3/accounts/index'
import { Route as ProtectedAccountManageS3IndexRouteImport } from './routes/_protected/account/manage-s3/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiHealthIndexRoute = ApiHealthIndexRouteImport.update({
  id: '/api/health/',
  path: '/api/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountIndexRoute = ProtectedAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAccountRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiS3AccountsIndexRoute = ApiS3AccountsIndexRouteImport.update({
  id: '/api/s3/accounts/',
  path: '/api/s3/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountManageS3IndexRoute =
  ProtectedAccountManageS3IndexRouteImport.update({
    id: '/manage-s3/',
    path: '/manage-s3/',
    getParentRoute: () => ProtectedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/account': typeof ProtectedAccountRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/': typeof ProtectedAccountIndexRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/account/manage-s3/': typeof ProtectedAccountManageS3IndexRoute
  '/api/s3/accounts/': typeof ApiS3AccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/about': typeof AboutIndexRoute
  '/signin': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account': typeof ProtectedAccountIndexRoute
  '/api/health': typeof ApiHealthIndexRoute
  '/account/manage-s3': typeof ProtectedAccountManageS3IndexRoute
  '/api/s3/accounts': typeof ApiS3AccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/account': typeof ProtectedAccountRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/about/': typeof AboutIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/account/': typeof ProtectedAccountIndexRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/_protected/account/manage-s3/': typeof ProtectedAccountManageS3IndexRoute
  '/api/s3/accounts/': typeof ApiS3AccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/about/'
    | '/signin/'
    | '/api/auth/$'
    | '/account/'
    | '/api/health/'
    | '/account/manage-s3/'
    | '/api/s3/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/signin'
    | '/api/auth/$'
    | '/account'
    | '/api/health'
    | '/account/manage-s3'
    | '/api/s3/accounts'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/account'
    | '/_protected/'
    | '/about/'
    | '/signin/'
    | '/api/auth/$'
    | '/_protected/account/'
    | '/api/health/'
    | '/_protected/account/manage-s3/'
    | '/api/s3/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthIndexRoute: typeof ApiHealthIndexRoute
  ApiS3AccountsIndexRoute: typeof ApiS3AccountsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/api/health'
      fullPath: '/api/health/'
      preLoaderRoute: typeof ApiHealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account/': {
      id: '/_protected/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof ProtectedAccountIndexRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3/accounts/': {
      id: '/api/s3/accounts/'
      path: '/api/s3/accounts'
      fullPath: '/api/s3/accounts/'
      preLoaderRoute: typeof ApiS3AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account/manage-s3/': {
      id: '/_protected/account/manage-s3/'
      path: '/manage-s3'
      fullPath: '/account/manage-s3/'
      preLoaderRoute: typeof ProtectedAccountManageS3IndexRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
  }
}

interface ProtectedAccountRouteChildren {
  ProtectedAccountIndexRoute: typeof ProtectedAccountIndexRoute
  ProtectedAccountManageS3IndexRoute: typeof ProtectedAccountManageS3IndexRoute
}

const ProtectedAccountRouteChildren: ProtectedAccountRouteChildren = {
  ProtectedAccountIndexRoute: ProtectedAccountIndexRoute,
  ProtectedAccountManageS3IndexRoute: ProtectedAccountManageS3IndexRoute,
}

const ProtectedAccountRouteWithChildren =
  ProtectedAccountRoute._addFileChildren(ProtectedAccountRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthIndexRoute: ApiHealthIndexRoute,
  ApiS3AccountsIndexRoute: ApiS3AccountsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
